import type { TaskTemplate } from '../../types/task';

export const INDIA_NATIONAL_TEMPLATES: TaskTemplate[] = [
  {
    id: 'in-national-document-pack',
    country: 'IN',
    language: 'en',
    category: 'documents',
    title: 'Essential ID Document Pack',
    description: 'Organize your core identity documents in one place for quick access.',
    requiredDocuments: ['aadhaar', 'pan', 'voter_id'],
    steps: [
      { id: 's1', order: 1, title: 'Gather Aadhaar copy', description: 'Front and back if available', isOptional: false },
      { id: 's2', order: 2, title: 'Add PAN card', isOptional: false },
      { id: 's3', order: 3, title: 'Add address proof', description: 'Utility bill or rental agreement', isOptional: true },
      { id: 's4', order: 4, title: 'Upload passport-size photo', isOptional: true },
    ],
    estimatedEffort: 'low',
    supportedUserTypes: ['student', 'parent', 'professional', 'family_manager', 'gig_worker'],
    tags: ['national', 'identity', 'starter'],
  },
  {
    id: 'in-student-pack',
    country: 'IN',
    language: 'en',
    category: 'education',
    title: 'Student Document Pack',
    description: 'Prepare marksheets, ID, and certificates for admissions and scholarships.',
    requiredDocuments: ['marksheet', 'aadhaar', 'income_certificate', 'caste_certificate'],
    steps: [
      { id: 's1', order: 1, title: 'Upload latest marksheet', isOptional: false },
      { id: 's2', order: 2, title: 'Check income certificate validity', isOptional: false },
      { id: 's3', order: 3, title: 'Add caste certificate if applicable', isOptional: true },
      { id: 's4', order: 4, title: 'Prepare passport photos', isOptional: false },
      { id: 's5', order: 5, title: 'Create admission checklist', isOptional: false },
    ],
    estimatedEffort: 'medium',
    supportedUserTypes: ['student', 'parent'],
    tags: ['national', 'student', 'education'],
  },
  {
    id: 'in-family-pack',
    country: 'IN',
    language: 'en',
    category: 'family_reminders',
    title: 'Family Admin Starter Pack',
    description: 'Set up family profiles and shared document reminders.',
    requiredDocuments: ['aadhaar', 'insurance', 'medical_prescription'],
    steps: [
      { id: 's1', order: 1, title: 'Add family members', isOptional: false },
      { id: 's2', order: 2, title: 'Assign documents to each member', isOptional: false },
      { id: 's3', order: 3, title: 'Set medicine reminders', isOptional: true },
      { id: 's4', order: 4, title: 'Track school fee receipts', isOptional: true },
    ],
    estimatedEffort: 'medium',
    supportedUserTypes: ['parent', 'family_manager', 'senior_citizen'],
    tags: ['national', 'family'],
  },
  {
    id: 'in-shopkeeper-pack',
    country: 'IN',
    language: 'en',
    category: 'business_admin',
    title: 'Shopkeeper Monthly Admin Pack',
    description: 'Organize UPI receipts, rent, and business documents monthly.',
    requiredDocuments: ['pan', 'bank_document', 'rental_agreement'],
    steps: [
      { id: 's1', order: 1, title: 'Save UPI receipts for the month', isOptional: false },
      { id: 's2', order: 2, title: 'Track rent payment proof', isOptional: false },
      { id: 's3', order: 3, title: 'Review GST/shop license expiry', isOptional: true },
      { id: 's4', order: 4, title: 'Set monthly reminder', isOptional: false },
    ],
    estimatedEffort: 'low',
    reminderScheduleDays: [1, 28],
    supportedUserTypes: ['shopkeeper', 'service_provider'],
    tags: ['national', 'business', 'receipts'],
  },
];
