import type { TaskTemplate } from '../../types/task';

export const MP_REGIONAL_TEMPLATES: TaskTemplate[] = [
  {
    id: 'mp-income-certificate',
    country: 'IN',
    state: 'MP',
    language: 'en',
    category: 'government_forms',
    title: 'MP Income Certificate Preparation',
    description: 'Prepare documents and steps to apply for an income certificate in Madhya Pradesh via e-District or Tehsil.',
    requiredDocuments: ['aadhaar', 'pan', 'voter_id', 'bank_document'],
    steps: [
      { id: 's1', order: 1, title: 'Verify Aadhaar is linked to mobile', isOptional: false },
      { id: 's2', order: 2, title: 'Collect income proof', description: 'Salary slip, self-declaration, or employer letter', isOptional: false },
      { id: 's3', order: 3, title: 'Gather address proof', description: 'Ration card, voter ID, or utility bill', isOptional: false },
      { id: 's4', order: 4, title: 'Get passport-size photos', isOptional: false },
      { id: 's5', order: 5, title: 'Visit e-District MP portal or Tehsil', description: 'Apply online or submit at Janpad Panchayat/Tehsil', isOptional: false },
      { id: 's6', order: 6, title: 'Pay applicable fee and save receipt', isOptional: false },
      { id: 's7', order: 7, title: 'Track application status', isOptional: false },
    ],
    officialLink: 'https://mpedistrict.gov.in/',
    warningNotes: [
      'Processing time varies by district — typically 7–15 working days.',
      'Income certificate validity is usually 1 financial year.',
      'TaskSetu does not submit on your behalf — this is a preparation checklist only.',
    ],
    estimatedEffort: 'medium',
    reminderScheduleDays: [3, 7, 14],
    supportedUserTypes: ['student', 'parent', 'farmer', 'gig_worker'],
    tags: ['mp', 'government', 'income-certificate'],
  },
  {
    id: 'mp-caste-certificate',
    country: 'IN',
    state: 'MP',
    language: 'en',
    category: 'government_forms',
    title: 'MP Caste Certificate Preparation',
    description: 'Checklist for SC/ST/OBC caste certificate application in Madhya Pradesh.',
    requiredDocuments: ['aadhaar', 'birth_certificate', 'voter_id'],
    steps: [
      { id: 's1', order: 1, title: 'Confirm caste category eligibility', isOptional: false },
      { id: 's2', order: 2, title: 'Collect parent/guardian caste certificate if available', isOptional: true },
      { id: 's3', order: 3, title: 'Get birth certificate or school leaving certificate', isOptional: false },
      { id: 's4', order: 4, title: 'Affidavit from competent authority if required', isOptional: true },
      { id: 's5', order: 5, title: 'Apply via e-District MP or local Tehsil', isOptional: false },
      { id: 's6', order: 6, title: 'Save application number for tracking', isOptional: false },
    ],
    officialLink: 'https://mpedistrict.gov.in/',
    warningNotes: [
      'First-time applicants may need field verification.',
      'Keep originals ready for Tehsil visit if requested.',
    ],
    estimatedEffort: 'high',
    supportedUserTypes: ['student', 'parent'],
    tags: ['mp', 'government', 'caste-certificate'],
  },
  {
    id: 'mp-domicile-certificate',
    country: 'IN',
    state: 'MP',
    language: 'en',
    category: 'government_forms',
    title: 'MP Domicile / Residence Certificate',
    description: 'Prepare domicile certificate for admissions, jobs, and government schemes in MP.',
    requiredDocuments: ['aadhaar', 'voter_id', 'birth_certificate', 'rental_agreement'],
    steps: [
      { id: 's1', order: 1, title: 'Prove continuous residence in MP', description: 'School records, voter ID, or property papers', isOptional: false },
      { id: 's2', order: 2, title: 'Collect address proof (minimum 3 years if required)', isOptional: false },
      { id: 's3', order: 3, title: 'Affidavit for domicile if applicable', isOptional: true },
      { id: 's4', order: 4, title: 'Apply on e-District MP portal', isOptional: false },
      { id: 's5', order: 5, title: 'Set follow-up reminder in 10 days', isOptional: false },
    ],
    officialLink: 'https://mpedistrict.gov.in/',
    warningNotes: ['Requirements may differ for students vs job applicants.'],
    estimatedEffort: 'medium',
    supportedUserTypes: ['student', 'parent', 'professional'],
    tags: ['mp', 'government', 'domicile'],
  },
  {
    id: 'mp-scholarship-pack',
    country: 'IN',
    state: 'MP',
    language: 'en',
    category: 'education',
    title: 'MP Scholarship Document Pack',
    description: 'Bundle documents commonly needed for state and central scholarships in MP.',
    requiredDocuments: ['aadhaar', 'marksheet', 'income_certificate', 'caste_certificate', 'bank_document'],
    steps: [
      { id: 's1', order: 1, title: 'Verify income certificate is current year', isOptional: false },
      { id: 's2', order: 2, title: 'Link Aadhaar to bank account', isOptional: false },
      { id: 's3', order: 3, title: 'Upload latest marksheet', isOptional: false },
      { id: 's4', order: 4, title: 'Add caste certificate if category-based scheme', isOptional: true },
      { id: 's5', order: 5, title: 'Check scholarship portal deadline', isOptional: false },
      { id: 's6', order: 6, title: 'Save application screenshot and reference ID', isOptional: false },
    ],
    officialLink: 'https://scholarshipportal.mp.gov.in/',
    warningNotes: ['Deadlines vary by scheme — set reminders early.'],
    estimatedEffort: 'medium',
    reminderScheduleDays: [7, 3, 1],
    supportedUserTypes: ['student', 'parent'],
    tags: ['mp', 'scholarship', 'education'],
  },
  {
    id: 'mp-student-exam-pack',
    country: 'IN',
    state: 'MP',
    language: 'en',
    category: 'education',
    title: 'MP Student Exam & Admission Pack',
    description: 'Prepare for board exams, MPBSE processes, and college admission document requirements.',
    requiredDocuments: ['aadhaar', 'marksheet', 'birth_certificate', 'domicile_certificate'],
    steps: [
      { id: 's1', order: 1, title: 'Confirm exam registration details', isOptional: false },
      { id: 's2', order: 2, title: 'Collect admit card and ID proof copies', isOptional: false },
      { id: 's3', order: 3, title: 'Prepare domicile if applying to state quota seats', isOptional: true },
      { id: 's4', order: 4, title: 'Organize 10th/12th marksheets and certificates', isOptional: false },
      { id: 's5', order: 5, title: 'Track counselling dates and document verification list', isOptional: false },
      { id: 's6', order: 6, title: 'Create WhatsApp share list for missing docs from family', isOptional: true },
    ],
    officialLink: 'https://mpbse.nic.in/',
    warningNotes: ['Keep both original and photocopies ready for verification centres.'],
    estimatedEffort: 'high',
    supportedUserTypes: ['student', 'parent'],
    tags: ['mp', 'exam', 'admission', 'education'],
  },
];
